**Necessary Imports**

In [44]:
import pandas as pd 
import numpy as np 
import re 
import matplotlib.pyplot as plt

**Loading the Necessary Files**

In [45]:
df = pd.read_csv(r"d:/Coding/Exploratory_Data_Analysis/data/Scraped/Unclean/current_bikes_scraped_hamrobazar.csv",on_bad_lines='skip')
df.head()

,Name,Price,Used For,Warranty,Transmission,Colour,Make Year,Features,Mileage,Engine (CC),Fuel,Kilometer Run,Types
0,honda dio 60lot urgent sell,96000,NaN,NaN,Manual,NaN,2014,NaN,35,110,Petrol,NaN,Scooty
1,Ns200 urgent on sell,120000,NaN,NaN,Manual,NaN,2016,NaN,35,200,Petrol,NaN,Sport
2,Honda Dio fresh condition scooter on sale,98000,NaN,NaN,Automatic,NaN,2016,NaN,45,106,Petrol,65000,Scooty
3,Honda aviator 041lot,195000,NaN,NaN,Manual,NaN,2023,NaN,NaN,NaN,Petrol,NaN,Scooty
4,Facino 95lot,85000,NaN,NaN,Manual,NaN,2018,NaN,NaN,NaN,Petrol,NaN,Scooty

In [46]:
print(df['Types'].unique())

['Scooty' 'Sport' 'Standard' 'Others' 'Dirt' 'Cruiser' nan 'Sports']

In [47]:
print(df['Types'].value_counts())

Types
Standard    680
Scooty      333
Sport       326
Dirt         67
Cruiser      65
Others       58
Sports        2
Name: count, dtype: int64

In [48]:
print(df[df['Types']=='Cruiser']['Name'])

137                  Meteor 350 ONE PIECE FOR SALE
143                                  HONDA CB350RS
149             2021 Model Java like new condition
170                                     Reborn 350
248                   Royal Enfield On Urgent Sale
                           ...
1450    2016 model avenger 150 (NUMBER 9703318215)
1454      Suzuki GZ 250 Japanese sale or exchange
1463                        Avenger 220 2020 Model
1479                          benelli leoncino 250
1489                        Suzuki GN 125 Japanese
Name: Name, Length: 65, dtype: object

In [49]:
mapping_dictionary = {
    'Scooty': 0,
    'Sport': 1,
    'Standard': 1,
    'Dirt': 1,
    'Others': 1,
    'Cruiser': 1,
    'Sports': 1,
    None: 0,  
}

In [50]:
df['Types']=df['Types'].map(mapping_dictionary)

In [51]:
df.head()

,Name,Price,Used For,Warranty,Transmission,Colour,Make Year,Features,Mileage,Engine (CC),Fuel,Kilometer Run,Types
0,honda dio 60lot urgent sell,96000,NaN,NaN,Manual,NaN,2014,NaN,35,110,Petrol,NaN,0.0
1,Ns200 urgent on sell,120000,NaN,NaN,Manual,NaN,2016,NaN,35,200,Petrol,NaN,1.0
2,Honda Dio fresh condition scooter on sale,98000,NaN,NaN,Automatic,NaN,2016,NaN,45,106,Petrol,65000,0.0
3,Honda aviator 041lot,195000,NaN,NaN,Manual,NaN,2023,NaN,NaN,NaN,Petrol,NaN,0.0
4,Facino 95lot,85000,NaN,NaN,Manual,NaN,2018,NaN,NaN,NaN,Petrol,NaN,0.0

In [52]:
df.drop(['Used For','Warranty','Transmission','Features','Colour'],axis=1,inplace=True)
df.head()

,Name,Price,Make Year,Mileage,Engine (CC),Fuel,Kilometer Run,Types
0,honda dio 60lot urgent sell,96000,2014,35,110,Petrol,NaN,0.0
1,Ns200 urgent on sell,120000,2016,35,200,Petrol,NaN,1.0
2,Honda Dio fresh condition scooter on sale,98000,2016,45,106,Petrol,65000,0.0
3,Honda aviator 041lot,195000,2023,NaN,NaN,Petrol,NaN,0.0
4,Facino 95lot,85000,2018,NaN,NaN,Petrol,NaN,0.0

In [53]:
df.isnull().sum()

Name               0
Price              0
Make Year         16
Mileage          818
Engine (CC)      596
Fuel              21
Kilometer Run    758
Types             15
dtype: int64

In [54]:
print(df['Fuel'].value_counts())

Fuel
Petrol      1502
Electric      19
Hybrid         3
Diesel         1
Name: count, dtype: int64

In [55]:
df = df[~df['Fuel'].isin(['Electric', 'Hybrid', 'Diesel'])]

In [56]:
print(df['Fuel'].value_counts())

Fuel
Petrol    1502
Name: count, dtype: int64

In [57]:
df.drop(['Fuel'],axis=1,inplace=True)

In [58]:
df.head()

,Name,Price,Make Year,Mileage,Engine (CC),Kilometer Run,Types
0,honda dio 60lot urgent sell,96000,2014,35,110,NaN,0.0
1,Ns200 urgent on sell,120000,2016,35,200,NaN,1.0
2,Honda Dio fresh condition scooter on sale,98000,2016,45,106,65000,0.0
3,Honda aviator 041lot,195000,2023,NaN,NaN,NaN,0.0
4,Facino 95lot,85000,2018,NaN,NaN,NaN,0.0

**Changing the columns into Snake Case**

In [59]:
df.columns = (
    df.columns               
      .str.lower()                  # convert to lowercase
      .str.replace('[^a-zA-Z0-9 ]', '', regex=True)   # remove special chars ()&./
      .str.replace(' +', '_', regex=True)  # convert spaces to underscores
)
df.head()

,name,price,make_year,mileage,engine_cc,kilometer_run,types
0,honda dio 60lot urgent sell,96000,2014,35,110,NaN,0.0
1,Ns200 urgent on sell,120000,2016,35,200,NaN,1.0
2,Honda Dio fresh condition scooter on sale,98000,2016,45,106,65000,0.0
3,Honda aviator 041lot,195000,2023,NaN,NaN,NaN,0.0
4,Facino 95lot,85000,2018,NaN,NaN,NaN,0.0

**Dropping Duplicate**

In [60]:
df.drop_duplicates(subset=["name"], keep="first")

,name,price,make_year,mileage,engine_cc,kilometer_run,types
0,honda dio 60lot urgent sell,96000,2014,35,110,NaN,0.0
1,Ns200 urgent on sell,120000,2016,35,200,NaN,1.0
2,Honda Dio fresh condition scooter on sale,98000,2016,45,106,65000,0.0
3,Honda aviator 041lot,195000,2023,NaN,NaN,NaN,0.0
4,Facino 95lot,85000,2018,NaN,NaN,NaN,0.0
...,...,...,...,...,...,...,...
1541,Pulsar Bike On Sale,122000,2016,40,150,300000,1.0
1542,Crf250l,1450000,2019,NaN,250,6000,1.0
1543,Royal Enfield Classic 350 for Sale!!!,350000,2014,NaN,346,42804,1.0
1544,pulsar 150 tw bike urgent sell,150000,2020,NaN,150,11000,1.0
1545,Fresh Dominar 400 CC for sale,420000,2019,28,400,18300,1.0

**Changing the KW to cc**

In [61]:
def convert_kw_to_cc(value):
    if pd.isna(value):
        return value
    
    # Convert to string for processing
    value_str = str(value).strip().lower()
    
    # Check if 'kw' is in the value
    if 'kw' in value_str:
        # Extract numeric part using regex
        match = re.search(r'(\d+\.?\d*)', value_str)
        if match:
            numeric_value = float(match.group(1))
            # Multiply by 24.25 and return
            return numeric_value * 24.25
    
    # Return original value if no 'kw' found
    return value

df['engine_cc']= df['engine_cc'].apply(convert_kw_to_cc)

**Cleaning Numeric Columns**

In [62]:

def clean_numeric_columns(df, columns):
    for col in columns:
        df[col] = df[col].astype(str).str.extract(r'(\d+(?:\.\d+)?)')
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

df = clean_numeric_columns(df,['make_year','mileage','engine_cc','kilometer_run','price','types'])
df.head()

,name,price,make_year,mileage,engine_cc,kilometer_run,types
0,honda dio 60lot urgent sell,96000,2014.0,35.0,110.0,NaN,0.0
1,Ns200 urgent on sell,120000,2016.0,35.0,200.0,NaN,1.0
2,Honda Dio fresh condition scooter on sale,98000,2016.0,45.0,106.0,65000.0,0.0
3,Honda aviator 041lot,195000,2023.0,NaN,NaN,NaN,0.0
4,Facino 95lot,85000,2018.0,NaN,NaN,NaN,0.0

**Since, ['engine_cc','make_year','price','mileage','kilometer_run'] are the critical columns thus, we are dropping those entries  where 2 out of 3 columns are missing. **

In [63]:
def sixty_percent_or_more_columns_missing(df,critical_columns):
    missing_count = df[critical_columns].isna().sum(axis=1)
    to_drop = missing_count >= 3
    print(f"Length of outliers:{len(df.loc[to_drop, critical_columns])}\n\n")

In [64]:
sixty_percent_or_more_columns_missing(df,['engine_cc', 'make_year', 'price','mileage','kilometer_run'])

Length of outliers:525

**Using capped_mputation of kilometers_run on the basis of make_year**

In [65]:
df['make_year'] = pd.to_numeric(df['make_year'], errors='coerce')
df['kilometer_run'] = pd.to_numeric(df['kilometer_run'], errors='coerce')
# Calculate actual km/year from existing data
df['km_per_year'] = df['kilometer_run'] / (2024 - df['make_year'])

Q3 = df['kilometer_run'].quantile(0.75)
Q1 = df['kilometer_run'].quantile(0.25)
IQR = Q3-Q1
# Get realistic median km/year from your dataset
cap_value = Q3 + 1.5 * IQR  # Use your actual rate but cap at Q3 + 1.5*IQR (standard outlier threshold)
actual_km_per_year = df['km_per_year'].median()  # Likely 5,000-8,000
print(f"Actual km/year in dataset: {actual_km_per_year}")

# Now impute using YOUR data's pattern
missing_mask = df['kilometer_run'].isna()
df.loc[missing_mask, 'kilometer_run'] = np.minimum(
    (2024 - df.loc[missing_mask, 'make_year']) * 4788,
    cap_value
)
df.drop('km_per_year',axis=1,inplace=True)

Actual km/year in dataset: 5000.0

In [66]:
sixty_percent_or_more_columns_missing(df,['engine_cc', 'make_year', 'price','mileage','kilometer_run'])

Length of outliers:15

**Imputing Mileage on the basis of engine_cc**

In [67]:
df['engine_cc'] = pd.to_numeric(df['engine_cc'], errors='coerce')
# Group by fuel type and engine size categories
df['engine_category'] = pd.cut(df['engine_cc'], 
                                bins=[0, 1200, 1600, 2000, 5000],
                                labels=['Small', 'Medium', 'Large', 'Very Large'])

# Impute with group median
df['mileage'] = df.groupby(['engine_cc'])['mileage'].transform(
    lambda x: x.fillna(x.median())
)

df.drop('engine_category', axis=1, inplace=True)

# Check result
print(df['mileage'].describe())

count      930.000000
mean       171.662903
std       3031.112994
min          2.000000
25%         35.000000
50%         40.000000
75%         45.000000
max      88628.000000
Name: mileage, dtype: float64

d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

**Discovery of Outliers in the Numeric Data**

In [68]:
def find_quartiles_and_outliers(columns):
    for column in columns:
        print(f"\n\n For the {column}")
        df[column] = pd.to_numeric(df[column],errors='coerce')
        Q1 = df[column].quantile(0.25)
        Q2 = df[column].mean()
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        print(f"Q1:{Q1} ,Q2:{Q2} ,Q3:{Q3} , IQR:{IQR}") 
        outliers = df[(df[column] < (Q1 - 1.5* IQR)) | (df[column] > (Q3 + 1.5 * IQR))]
        print(f"Number of Outliers: {len(outliers)}")

find_quartiles_and_outliers(['kilometer_run','engine_cc','price','mileage','make_year'])

 For the kilometer_run
Q1:14364.0 ,Q2:-32207.909151193635 ,Q3:33516.0 , IQR:19152.0
Number of Outliers: 26


 For the engine_cc
Q1:125.0 ,Q2:189.08871139510117 ,Q3:220.0 , IQR:95.0
Number of Outliers: 43


 For the price
Q1:115000.0 ,Q2:224701.85554826 ,Q3:250000.0 , IQR:135000.0
Number of Outliers: 97


 For the mileage
Q1:35.0 ,Q2:171.66290322580645 ,Q3:45.0 , IQR:10.0
Number of Outliers: 18


 For the make_year
Q1:2017.0 ,Q2:3424.856668878567 ,Q3:2021.0 , IQR:4.0
Number of Outliers: 95

Special for Kilometers Run

In [69]:
def find_quartiles_and_outliers_print(columns):
    for column in columns:
        print(f"\n\n For the {column}")
        df[column] = pd.to_numeric(df[column],errors='coerce')
        Q1 = df[column].quantile(0.25)
        Q2 = df[column].mean()
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        print(f"Q1:{Q1} ,Q2:{Q2} ,Q3:{Q3} , IQR:{IQR}") 
        outliers = df[(df[column] < (Q1 - 1.5* IQR)) | (df[column] > (Q3 + 1.5 * IQR))]
        print(outliers[column])
        print(f"Number of Outliers: {len(outliers)}")

In [70]:
find_quartiles_and_outliers_print(['kilometer_run'])

 For the kilometer_run
Q1:14364.0 ,Q2:-32207.909151193635 ,Q3:33516.0 , IQR:19152.0
2          65000.0
23       -268128.0
73        120000.0
97         77960.0
114        90000.0
181       720000.0
229       190000.0
414      -258552.0
432        75000.0
493        80000.0
504        76000.0
505        76000.0
518        67000.0
562        70000.0
581        89000.0
606    -87088932.0
819        74000.0
1203      100000.0
1345     -234612.0
1347       75000.0
1444       65000.0
1458      150000.0
1489       84000.0
1512      123456.0
1539       78247.0
1541      300000.0
Name: kilometer_run, dtype: float64
Number of Outliers: 26

In [71]:
upper_bound=100000
lower_bound=0
df['kilometer_run'] = df['kilometer_run'].clip(upper=upper_bound,lower=lower_bound)
find_quartiles_and_outliers_print(['kilometer_run'])

 For the kilometer_run
Q1:14364.0 ,Q2:25427.23673740053 ,Q3:33516.0 , IQR:19152.0
2        65000.0
73      100000.0
97       77960.0
114      90000.0
181     100000.0
229     100000.0
432      75000.0
493      80000.0
504      76000.0
505      76000.0
518      67000.0
562      70000.0
581      89000.0
819      74000.0
1203    100000.0
1347     75000.0
1444     65000.0
1458    100000.0
1489     84000.0
1512    100000.0
1539     78247.0
1541    100000.0
Name: kilometer_run, dtype: float64
Number of Outliers: 22

**Special for Make Year**

In [72]:
find_quartiles_and_outliers_print(['make_year'])

 For the make_year
Q1:2017.0 ,Q2:3424.856668878567 ,Q3:2021.0 , IQR:4.0
9       2010.0
14      2009.0
21      2010.0
23      2080.0
27      2005.0
         ...
1512    1234.0
1514    2000.0
1521    2009.0
1537       2.0
1539       1.0
Name: make_year, Length: 95, dtype: float64
Number of Outliers: 95

In [73]:
print(df['make_year'].value_counts())

make_year
2021.0       242
2019.0       166
2017.0       155
2018.0       143
2020.0       138
2016.0       128
2022.0       127
2015.0        70
2023.0        69
2024.0        64
2025.0        30
2010.0        30
2013.0        27
2014.0        23
2011.0        16
2012.0        14
2009.0         8
2008.0         8
2007.0         7
0.0            7
2005.0         3
2000.0         3
2075.0         2
2080.0         2
2003.0         2
2078.0         2
1990.0         2
2006.0         2
2001.0         2
2079.0         1
201.0          1
2004.0         1
2028.0         1
20213.0        1
102000.0       1
2065.0         1
1016.0         1
2024398.0      1
2073.0         1
1994.0         1
1998.0         1
1234.0         1
2.0            1
1.0            1
Name: count, dtype: int64

In [74]:
upper_bound=2024
lower_bound=2000
df = df[(df['make_year'] >= lower_bound) & (df['make_year'] <= upper_bound)]
find_quartiles_and_outliers_print(['make_year'])

 For the make_year
Q1:2017.0 ,Q2:2018.4813535911603 ,Q3:2021.0 , IQR:4.0
9       2010.0
14      2009.0
21      2010.0
27      2005.0
37      2008.0
         ...
1485    2005.0
1490    2010.0
1506    2007.0
1514    2000.0
1521    2009.0
Name: make_year, Length: 66, dtype: float64
Number of Outliers: 66

**Now for the mileage**

In [75]:
find_quartiles_and_outliers_print(['mileage'])

 For the mileage
Q1:35.0 ,Q2:177.45286195286195 ,Q3:45.0 , IQR:10.0
5          65.0
430        65.0
557        65.0
600     25000.0
671       353.0
700         2.0
775        18.0
810        16.0
813     88628.0
814        18.0
945       450.0
1305       65.0
1394       65.0
1426       15.0
1460     9000.0
1462       18.0
Name: mileage, dtype: float64
Number of Outliers: 16

**Keeping price,engine_cc outliers because they are genuine data, Capping the mileage outliers at the 65**

In [76]:
upper_bound=65
lower_bound=16
df = df[(df['mileage'] >= lower_bound) & (df['mileage'] <= upper_bound)]
find_quartiles_and_outliers_print(['mileage'])

 For the mileage
Q1:35.0 ,Q2:39.210972850678736 ,Q3:45.0 , IQR:10.0
5       65.0
430     65.0
557     65.0
775     18.0
810     16.0
814     18.0
1305    65.0
1394    65.0
1462    18.0
Name: mileage, dtype: float64
Number of Outliers: 9

In [77]:
df = df[df['mileage'] <= 2000000]

In [78]:
df.isnull().sum()

name             0
price            0
make_year        0
mileage          0
engine_cc        0
kilometer_run    0
types            0
dtype: int64

In [79]:
df.head()

,name,price,make_year,mileage,engine_cc,kilometer_run,types
0,honda dio 60lot urgent sell,96000,2014.0,35.0,110.0,47880.0,0.0
1,Ns200 urgent on sell,120000,2016.0,35.0,200.0,38304.0,1.0
2,Honda Dio fresh condition scooter on sale,98000,2016.0,45.0,106.0,65000.0,0.0
5,Honda Shine 125 Model 2024,235000,2024.0,65.0,125.0,9250.0,1.0
6,Yamaha Mt 15,360000,2022.0,45.0,155.0,20000.0,1.0

Finally changing make year into age.

In [80]:
df['age'] = 2025 - df['make_year']
df.drop('make_year',axis=1,inplace=True)
df.head()

,name,price,mileage,engine_cc,kilometer_run,types,age
0,honda dio 60lot urgent sell,96000,35.0,110.0,47880.0,0.0,11.0
1,Ns200 urgent on sell,120000,35.0,200.0,38304.0,1.0,9.0
2,Honda Dio fresh condition scooter on sale,98000,45.0,106.0,65000.0,0.0,9.0
5,Honda Shine 125 Model 2024,235000,65.0,125.0,9250.0,1.0,1.0
6,Yamaha Mt 15,360000,45.0,155.0,20000.0,1.0,3.0

**Saving the Cleaned Data**

In [81]:
df.to_csv("D:/Coding/Exploratory_Data_Analysis/data/Scraped/Clean/cleaned_bike_data.csv", index=False)