**Necessary Imports**

In [358]:
import pandas as pd 
import numpy as np 
import re 
import matplotlib.pyplot as plt

**Loading the Necessary Files**

In [359]:
df = pd.read_csv(r"d:/Coding/Exploratory_Data_Analysis/data/Scraped/Unclean/current_cars_scraped_hamrobazar.csv",on_bad_lines='skip')
df.head()

,Name,Price,Used For,Warranty,Transmission,Colour,Make Year,Features,Mileage,Engine (CC),Fuel,Kilometer Run,Types
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,NaN,NaN,Manual2WD,NaN,2007,NaN,15,1600,Petrol,NaN,Sedan
1,Hyundai i10 2009model with option,1055000.0,NaN,NaN,Manual - 2WD,Dark Blue,2009,Fresh car with great engine and on sale plus c...,16,1100,Petrol,NaN,Mid Size Hatchback
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,Personal,NaN,Auto2WD,Marun,2014,Basic full option,15-18,1100 CC,Petrol,77000,MidSizeHatchback
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,Personal,NaN,Auto2WD,Marun,2013,Basic full option,15-18,1100 CC,Petrol,77000,MidSizeHatchback
4,i10 magna 1200cc,1175000.0,NaN,NaN,Manual - 2WD,blue,2009,power steering power windows ac heater,14,1200,Petrol,62000,Small Hatchback

**Changing the columns into Snake Case**

In [360]:
df.columns = (
    df.columns               
      .str.lower()                  # convert to lowercase
      .str.replace('[^a-zA-Z0-9 ]', '', regex=True)   # remove special chars ()&./
      .str.replace(' +', '_', regex=True)  # convert spaces to underscores
)
df.head()

,name,price,used_for,warranty,transmission,colour,make_year,features,mileage,engine_cc,fuel,kilometer_run,types
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,NaN,NaN,Manual2WD,NaN,2007,NaN,15,1600,Petrol,NaN,Sedan
1,Hyundai i10 2009model with option,1055000.0,NaN,NaN,Manual - 2WD,Dark Blue,2009,Fresh car with great engine and on sale plus c...,16,1100,Petrol,NaN,Mid Size Hatchback
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,Personal,NaN,Auto2WD,Marun,2014,Basic full option,15-18,1100 CC,Petrol,77000,MidSizeHatchback
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,Personal,NaN,Auto2WD,Marun,2013,Basic full option,15-18,1100 CC,Petrol,77000,MidSizeHatchback
4,i10 magna 1200cc,1175000.0,NaN,NaN,Manual - 2WD,blue,2009,power steering power windows ac heater,14,1200,Petrol,62000,Small Hatchback

**Dropping Duplicate**

In [361]:
df.drop_duplicates(subset=["name"], keep="first")

,name,price,used_for,warranty,transmission,colour,make_year,features,mileage,engine_cc,fuel,kilometer_run,types
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,NaN,NaN,Manual2WD,NaN,2007,NaN,15,1600,Petrol,NaN,Sedan
1,Hyundai i10 2009model with option,1055000.0,NaN,NaN,Manual - 2WD,Dark Blue,2009,Fresh car with great engine and on sale plus c...,16,1100,Petrol,NaN,Mid Size Hatchback
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,Personal,NaN,Auto2WD,Marun,2014,Basic full option,15-18,1100 CC,Petrol,77000,MidSizeHatchback
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,Personal,NaN,Auto2WD,Marun,2013,Basic full option,15-18,1100 CC,Petrol,77000,MidSizeHatchback
4,i10 magna 1200cc,1175000.0,NaN,NaN,Manual - 2WD,blue,2009,power steering power windows ac heater,14,1200,Petrol,62000,Small Hatchback
...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,Ashoka Layland 1478 cc,730000.0,pickup,3 month,Manual4WD,Skyblue,2016,70hp GVW = 2590,19.6,1478,Diesel,NaN,Pickup
952,Ford EcoSport Titanium,2799999.0,NaN,NaN,Manual2WD,Silver,2015,NaN,NaN,1498,Petrol,25000,CompactSUV
953,Swift Dzire(car),1280000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
954,Renault kiger on sale,2400000.0,1year,NaN,Manual - 2WD,blue,2021,NaN,14,999,Petrol,14500,Compact SUV
955,Alto Car Urgent Sell भीसा लागेको ले,520000.0,Wonself,No,Auto - 2WD,Silver,2002,NaN,15,1061,Petrol,151,Others

**Checking Null Values**

In [362]:
df.isnull().sum()

name               0
price              0
used_for         648
warranty         789
transmission      13
colour           195
make_year          9
features         513
mileage          529
engine_cc        184
fuel               9
kilometer_run    259
types             15
dtype: int64

Dropping used_for, warranty, colour and features.

In [363]:
df.drop(['used_for','warranty','colour','features'],axis=1,inplace=True)
df.head()

,name,price,transmission,make_year,mileage,engine_cc,fuel,kilometer_run,types
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,Manual2WD,2007,15,1600,Petrol,NaN,Sedan
1,Hyundai i10 2009model with option,1055000.0,Manual - 2WD,2009,16,1100,Petrol,NaN,Mid Size Hatchback
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,Auto2WD,2014,15-18,1100 CC,Petrol,77000,MidSizeHatchback
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,Auto2WD,2013,15-18,1100 CC,Petrol,77000,MidSizeHatchback
4,i10 magna 1200cc,1175000.0,Manual - 2WD,2009,14,1200,Petrol,62000,Small Hatchback

**Changing the KW to cc**

In [364]:
def convert_kw_to_cc(value):
    if pd.isna(value):
        return value
    
    # Convert to string for processing
    value_str = str(value).strip().lower()
    
    # Check if 'kw' is in the value
    if 'kw' in value_str:
        # Extract numeric part using regex
        match = re.search(r'(\d+\.?\d*)', value_str)
        if match:
            numeric_value = float(match.group(1))
            # Multiply by 24.25 and return
            return numeric_value * 24.25
    
    # Return original value if no 'kw' found
    return value

df['engine_cc']= df['engine_cc'].apply(convert_kw_to_cc)

**Cleaning Numeric Columns**

In [365]:

def clean_numeric_columns(df, columns):
    for col in columns:
        df[col] = df[col].astype(str).str.extract(r'(\d+(?:\.\d+)?)')
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

df = clean_numeric_columns(df,['make_year','mileage','engine_cc','kilometer_run'])
df.head()

,name,price,transmission,make_year,mileage,engine_cc,fuel,kilometer_run,types
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,Manual2WD,2007.0,15.0,1600.0,Petrol,NaN,Sedan
1,Hyundai i10 2009model with option,1055000.0,Manual - 2WD,2009.0,16.0,1100.0,Petrol,NaN,Mid Size Hatchback
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,Auto2WD,2014.0,15.0,1100.0,Petrol,77000.0,MidSizeHatchback
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,Auto2WD,2013.0,15.0,1100.0,Petrol,77000.0,MidSizeHatchback
4,i10 magna 1200cc,1175000.0,Manual - 2WD,2009.0,14.0,1200.0,Petrol,62000.0,Small Hatchback

**Since, ['engine_cc','make_year','price','mileage','kilometer_run'] are the critical columns thus, we are dropping those entries  where 2 out of 3 columns are missing. **

In [366]:
print(df['price'].isna().sum())

0

In [367]:
def sixty_percent_or_more_columns_missing(df,critical_columns):
    missing_count = df[critical_columns].isna().sum(axis=1)
    to_drop = missing_count >= 3
    print(f"Length of outliers:{len(df.loc[to_drop, critical_columns])}\n\n")

In [368]:
sixty_percent_or_more_columns_missing(df,['engine_cc', 'make_year', 'price','mileage','kilometer_run'])

Length of outliers:128

**Using capped_mputation of kilometers_run on the basis of make_year**

In [369]:
df['make_year'] = pd.to_numeric(df['make_year'], errors='coerce')
df['kilometer_run'] = pd.to_numeric(df['kilometer_run'], errors='coerce')
# Calculate actual km/year from existing data
df['km_per_year'] = df['kilometer_run'] / (2024 - df['make_year'])

# Get realistic median km/year from your dataset
cap_value = 66000 + 1.5 * 34000  # Use your actual rate but cap at Q3 + 1.5*IQR (standard outlier threshold)
actual_km_per_year = df['km_per_year'].median()  # Likely 5,000-8,000
print(f"Actual km/year in dataset: {actual_km_per_year}")

# Now impute using YOUR data's pattern
missing_mask = df['kilometer_run'].isna()
df.loc[missing_mask, 'kilometer_run'] = np.minimum(
    (2024 - df.loc[missing_mask, 'make_year']) * 4788,
    cap_value
)
df.drop('km_per_year',axis=1,inplace=True)

Actual km/year in dataset: 6186.147186147186

In [370]:
df.isnull().sum()

name               0
price              0
transmission      13
make_year         10
mileage          532
engine_cc        187
fuel               9
kilometer_run      9
types             15
dtype: int64

**Imputing Mileage on the basis of engine_cc**

In [371]:
df['engine_cc'] = pd.to_numeric(df['engine_cc'], errors='coerce')
# Group by fuel type and engine size categories
df['engine_category'] = pd.cut(df['engine_cc'], 
                                bins=[0, 1200, 1600, 2000, 5000],
                                labels=['Small', 'Medium', 'Large', 'Very Large'])

# Impute with group median
df['mileage'] = df.groupby(['fuel', 'engine_category'])['mileage'].transform(
    lambda x: x.fillna(x.median())
)

df.drop('engine_category', axis=1, inplace=True)

# Check result
print(df['mileage'].describe())

count      756.000000
mean       336.953571
std       3996.869462
min          4.000000
25%         13.000000
50%         14.000000
75%         15.000000
max      65000.000000
Name: mileage, dtype: float64

C:\Users\LEGION\AppData\Local\Temp\ipykernel_18360\3376968997.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df['mileage'] = df.groupby(['fuel', 'engine_category'])['mileage'].transform(
d:\Coding\Exploratory_Data_Analysis\.EDA\Lib\site-packages\numpy\lib\_nanfunctions_impl.py:1214: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

In [372]:
df.isnull().sum()

name               0
price              0
transmission      13
make_year         10
mileage          200
engine_cc        187
fuel               9
kilometer_run      9
types             15
dtype: int64

**Mapping Types into Certain Number of Categories**

In [373]:
df['types'].unique()

array(['Sedan', 'Mid Size Hatchback', 'MidSizeHatchback',
       'Small Hatchback', 'Van', 'SUV / Jeep', 'Pickup', 'Compact SUV',
       'Bus', 'CompactSUV', 'SUVJeep', 'SmallHatchback', 'Others', nan,
       'Truck'], dtype=object)

In [374]:

mapping_dictionary = {
    'Sedan': 'Sedan',
    'Mid Size Hatchback': 'Hatchback',
    'MidSizeHatchback': 'Hatchback',
    'Small Hatchback': 'Hatchback',
    'SmallHatchback': 'Hatchback',
    'Van': 'Van',
    'SUV / Jeep': 'SUV',
    'Compact SUV': 'SUV',
    'CompactSUV': 'SUV',
    'SUVJeep': 'SUV',
    'Pickup': 'Truck',
    'Truck': 'Truck',
    'Bus': 'Others',
    'Others': 'Others',
    None: 'Others',  
}

In [375]:
df['types'] = df['types'].map(mapping_dictionary)

In [376]:
df.head()

,name,price,transmission,make_year,mileage,engine_cc,fuel,kilometer_run,types
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,Manual2WD,2007.0,15.0,1600.0,Petrol,81396.0,Sedan
1,Hyundai i10 2009model with option,1055000.0,Manual - 2WD,2009.0,16.0,1100.0,Petrol,71820.0,Hatchback
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,Auto2WD,2014.0,15.0,1100.0,Petrol,77000.0,Hatchback
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,Auto2WD,2013.0,15.0,1100.0,Petrol,77000.0,Hatchback
4,i10 magna 1200cc,1175000.0,Manual - 2WD,2009.0,14.0,1200.0,Petrol,62000.0,Hatchback

**Removing Currency Symbol**

In [377]:
# df['price'] = df['price'].str.replace("रू.","",regex=False).str.replace(",","",regex=False).str.strip() #removes the rupee symbol and commas in the price. 
# df.loc[0,'price']=2475000
# df.head()

There are some listings with name in Nepali but they are kept as it is because it is very difficult to extend semantic meaning from them.

**Changing the transmission column into transmission_type and drive**

In [378]:
def split_transmisson(value):
    
    #first, let us check if the value is none. 
    if pd.isna(value):
        return (None,None)

    #Lets seperate by space
    value = value.strip()

    #If - is in the value then seperate by that value
    if '-' in value:
        parts = [p.strip() for p in value.split('-')]
        if len(parts) == 2:
            transmission_type = parts[0]
            drive = parts[1]
            return (transmission_type, drive)

    #Finally if the - doesn't exist we seperate alphabetic and numeric/WD parts 
    match = re.match(r"([A-Za-z]+)(.*)", value)
    if match:
        transmission_type = match.group(1)
        drive = match.group(2)
        return(transmission_type,drive)

    return(value,None)  

df[['transmisson_type','drive']] = df['transmission'].apply(lambda x: pd.Series(split_transmisson(x)))
df.drop('transmission', axis=1, inplace=True)
df.head()

,name,price,make_year,mileage,engine_cc,fuel,kilometer_run,types,transmisson_type,drive
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,2007.0,15.0,1600.0,Petrol,81396.0,Sedan,Manual,2WD
1,Hyundai i10 2009model with option,1055000.0,2009.0,16.0,1100.0,Petrol,71820.0,Hatchback,Manual,2WD
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,2014.0,15.0,1100.0,Petrol,77000.0,Hatchback,Auto,2WD
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,2013.0,15.0,1100.0,Petrol,77000.0,Hatchback,Auto,2WD
4,i10 magna 1200cc,1175000.0,2009.0,14.0,1200.0,Petrol,62000.0,Hatchback,Manual,2WD

**Discovery of Outliers in the Numeric Data**

In [379]:
def find_quartiles_and_outliers(columns):
    for column in columns:
        print(f"\n\n For the {column}")
        df[column] = pd.to_numeric(df[column],errors='coerce')
        Q1 = df[column].quantile(0.25)
        Q2 = df[column].mean()
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        print(f"Q1:{Q1} ,Q2:{Q2} ,Q3:{Q3} , IQR:{IQR}") 
        outliers = df[(df[column] < (Q1 - 1.5* IQR)) | (df[column] > (Q3 + 1.5 * IQR))]
        print(f"Number of Outliers: {len(outliers)}")

find_quartiles_and_outliers(['kilometer_run','engine_cc','price','mileage','make_year'])

 For the kilometer_run
Q1:33516.0 ,Q2:-30578.385427666315 ,Q3:72169.0 , IQR:38653.0
Number of Outliers: 22


 For the engine_cc
Q1:1196.0 ,Q2:1659.314066970091 ,Q3:1600.0 , IQR:404.0
Number of Outliers: 113


 For the price
Q1:1050000.0 ,Q2:3737661.887656904 ,Q3:3000000.0 , IQR:1950000.0
Number of Outliers: 66


 For the mileage
Q1:13.0 ,Q2:336.9535714285714 ,Q3:15.0 , IQR:2.0
Number of Outliers: 82


 For the make_year
Q1:2010.0 ,Q2:2048.8076109936574 ,Q3:2019.0 , IQR:9.0
Number of Outliers: 35

Special for Kilometers Run

In [380]:
def find_quartiles_and_outliers_print(columns):
    for column in columns:
        print(f"\n\n For the {column}")
        df[column] = pd.to_numeric(df[column],errors='coerce')
        Q1 = df[column].quantile(0.25)
        Q2 = df[column].mean()
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        print(f"Q1:{Q1} ,Q2:{Q2} ,Q3:{Q3} , IQR:{IQR}") 
        outliers = df[(df[column] < (Q1 - 1.5* IQR)) | (df[column] > (Q3 + 1.5 * IQR))]
        print(outliers[column])
        print(f"Number of Outliers: {len(outliers)}")

In [381]:
find_quartiles_and_outliers_print(['kilometer_run'])

 For the kilometer_run
Q1:33516.0 ,Q2:-30578.385427666315 ,Q3:72169.0 , IQR:38653.0
65       650000.0
84       950000.0
144      730000.0
169      170000.0
189     1500000.0
231      132000.0
236      450000.0
277      640000.0
360      375000.0
389      150000.0
393   -86116968.0
409      150000.0
479      350000.0
526      140000.0
538      200000.0
660      152000.0
691      590467.0
701      200000.0
725      381355.0
736      147108.0
744      500000.0
896      440000.0
Name: kilometer_run, dtype: float64
Number of Outliers: 22

There is one negative value, making it positive and Removing the values more than 180000, since they are in millions.

In [382]:
upper_bound=6000
df['engine_cc']=df['engine_cc'].clip(upper=upper_bound)

In [383]:
upper_bound=180000
lower_bound=0
df['kilometer_run'] = df['kilometer_run'].clip(upper=upper_bound,lower=lower_bound)
find_quartiles_and_outliers_print(['kilometer_run'])

 For the kilometer_run
Q1:33516.0 ,Q2:54652.51425554382 ,Q3:72169.0 , IQR:38653.0
65     180000.0
84     180000.0
144    180000.0
169    170000.0
189    180000.0
231    132000.0
236    180000.0
277    180000.0
360    180000.0
389    150000.0
409    150000.0
479    180000.0
526    140000.0
538    180000.0
660    152000.0
691    180000.0
701    180000.0
725    180000.0
736    147108.0
744    180000.0
896    180000.0
Name: kilometer_run, dtype: float64
Number of Outliers: 21

**Special for Make Year**

In [384]:
find_quartiles_and_outliers_print(['make_year'])

 For the make_year
Q1:2010.0 ,Q2:2048.8076109936574 ,Q3:2019.0 , IQR:9.0
77         1.0
84      1990.0
124    30000.0
173     1993.0
183     1995.0
189     1994.0
256     1992.0
270     1995.0
325     1015.0
374     1992.0
393    20010.0
409     1990.0
538     1991.0
584       17.0
623     1995.0
624     1995.0
660     1993.0
714     1978.0
722     1963.0
724     1954.0
727     1981.0
739     1970.0
742     1995.0
766     1964.0
767     1967.0
835     1996.0
850        0.0
853       19.0
865        1.0
880     1996.0
904     1994.0
910      201.0
921     1968.0
927     1991.0
944     1992.0
Name: make_year, dtype: float64
Number of Outliers: 35

Dropping 0 values, Manually changing 2069 and 2060 to AD, 13 to 2013 and 207 and 202 to 2007 and 2002

In [385]:
df = df.drop([77,124,850,865,910])
df.loc[393,'make_year']= 2010
df.loc[584,'make_year']= 2017
df.loc[853,'make_year']= 2019

find_quartiles_and_outliers_print(['make_year'])

 For the make_year
Q1:2010.0 ,Q2:2012.7194473963868 ,Q3:2019.0 , IQR:9.0
84     1990.0
173    1993.0
183    1995.0
189    1994.0
256    1992.0
270    1995.0
325    1015.0
374    1992.0
409    1990.0
538    1991.0
623    1995.0
624    1995.0
660    1993.0
714    1978.0
722    1963.0
724    1954.0
727    1981.0
739    1970.0
742    1995.0
766    1964.0
767    1967.0
835    1996.0
880    1996.0
904    1994.0
921    1968.0
927    1991.0
944    1992.0
Name: make_year, dtype: float64
Number of Outliers: 27

**Now for the mileage**

In [386]:
find_quartiles_and_outliers_print(['mileage'])

 For the mileage
Q1:13.0 ,Q2:338.68603723404254 ,Q3:15.0 , IQR:2.0
11        23.0
15     47000.0
28       120.0
35       650.0
46        19.0
        ...
914    59272.0
919       20.0
929       28.0
950       20.0
951       19.6
Name: mileage, Length: 81, dtype: float64
Number of Outliers: 81

**Keeping price,engine_cc outliers because they are genuine data, Capping the mileage outliers at the IQR**

In [387]:
Q1_m = df['mileage'].quantile(0.25)
Q3_m = df['mileage'].quantile(0.75)
IQR_m = Q3_m - Q1_m
df['mileage'] = df['mileage'].clip(
    lower=Q1_m - 1.5*IQR_m,
    upper=Q3_m + 1.5*IQR_m
)

Removing the ones with both mileage and engine_cc null.

In [388]:
df = df[~((df['engine_cc'].isnull()) & (df['mileage'].isnull()))]

**Handling the missing Values**

In [389]:
print(df['kilometer_run'].isna().sum())
print(df['price'].isna().sum())
print(df['engine_cc'].isna().sum())
print(df['mileage'].isna().sum())
print(df['make_year'].isna().sum())

0
0
0
13
1

Using median and mode for the numerical data.

In [390]:
df['mileage'] = df['mileage'].fillna(df['mileage'].median())
df['make_year'] = df['make_year'].fillna(df['make_year'].median())

Binary Encoding for Transmission Type

In [391]:
print(df['transmisson_type'].value_counts())

transmisson_type
Manual           581
Auto             177
Manual Gear        2
PowerSteering      1
Name: count, dtype: int64

Keeping power steering also as manual because it is too small dataset to be another feature and mostly power steering is used in heavy vehicle.

In [392]:
df['is_automatic'] = (df['transmisson_type'] == 'Auto').astype(int)
df.drop('transmisson_type', axis=1, inplace=True)

In [393]:
df.head()

,name,price,make_year,mileage,engine_cc,fuel,kilometer_run,types,drive,is_automatic
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,2007.0,15.0,1600.0,Petrol,81396.0,Sedan,2WD,0
1,Hyundai i10 2009model with option,1055000.0,2009.0,16.0,1100.0,Petrol,71820.0,Hatchback,2WD,0
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,2014.0,15.0,1100.0,Petrol,77000.0,Hatchback,2WD,1
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,2013.0,15.0,1100.0,Petrol,77000.0,Hatchback,2WD,1
4,i10 magna 1200cc,1175000.0,2009.0,14.0,1200.0,Petrol,62000.0,Hatchback,2WD,0

Binary Encoding for Drive

In [394]:
print(df['drive'].value_counts())

drive
2WD     604
4WD     154
          1
2 WD      1
4 WD      1
Name: count, dtype: int64

Keeping others at 2WD

In [395]:
df['is_4WD'] = ((df['drive'] == '4WD') | (df['drive'] == '4 WD')).astype(int)
df.drop('drive', axis=1, inplace=True)

In [396]:
df.head()

,name,price,make_year,mileage,engine_cc,fuel,kilometer_run,types,is_automatic,is_4WD
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,2007.0,15.0,1600.0,Petrol,81396.0,Sedan,0,0
1,Hyundai i10 2009model with option,1055000.0,2009.0,16.0,1100.0,Petrol,71820.0,Hatchback,0,0
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,2014.0,15.0,1100.0,Petrol,77000.0,Hatchback,1,0
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,2013.0,15.0,1100.0,Petrol,77000.0,Hatchback,1,0
4,i10 magna 1200cc,1175000.0,2009.0,14.0,1200.0,Petrol,62000.0,Hatchback,0,0

Encoding for Fuel

In [397]:
print(df['fuel'].value_counts())

fuel
Petrol      552
Diesel      181
Electric     27
Hybrid        5
Name: count, dtype: int64

Ordinal Encoding

In [398]:
fuel_order = {
    "Petrol": 1,
    "Diesel": 2,
    "Electric": 3,
    "Hybrid": 4
}

df['fuel'] = df['fuel'].map(fuel_order)
df.head()

,name,price,make_year,mileage,engine_cc,fuel,kilometer_run,types,is_automatic,is_4WD
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,2007.0,15.0,1600.0,1,81396.0,Sedan,0,0
1,Hyundai i10 2009model with option,1055000.0,2009.0,16.0,1100.0,1,71820.0,Hatchback,0,0
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,2014.0,15.0,1100.0,1,77000.0,Hatchback,1,0
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,2013.0,15.0,1100.0,1,77000.0,Hatchback,1,0
4,i10 magna 1200cc,1175000.0,2009.0,14.0,1200.0,1,62000.0,Hatchback,0,0

Encoding for types

In [399]:
print(len(df))

765

In [400]:
print(df['types'].isna().sum())

6

In [401]:
print(df['types'].value_counts())

types
SUV          294
Hatchback    266
Sedan        108
Truck         41
Van           29
Others        21
Name: count, dtype: int64

Ordinal Encoding

In [402]:
types_order = {
    "SUV": 1,
    "Hatchback": 2,
    "Sedan": 3,
    "Truck": 4,
    "Van":5,
    "Others":6
}

df['types'] = df['types'].map(types_order)
df.head()

,name,price,make_year,mileage,engine_cc,fuel,kilometer_run,types,is_automatic,is_4WD
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,2007.0,15.0,1600.0,1,81396.0,3.0,0,0
1,Hyundai i10 2009model with option,1055000.0,2009.0,16.0,1100.0,1,71820.0,2.0,0,0
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,2014.0,15.0,1100.0,1,77000.0,2.0,1,0
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,2013.0,15.0,1100.0,1,77000.0,2.0,1,0
4,i10 magna 1200cc,1175000.0,2009.0,14.0,1200.0,1,62000.0,2.0,0,0

Finally changing make year into age.

In [403]:
df['age'] = 2025 - df['make_year']
df.drop('make_year',axis=1,inplace=True)
df.head()

,name,price,mileage,engine_cc,fuel,kilometer_run,types,is_automatic,is_4WD,age
0,Nissan Sunny 1.6 fully fresh 9803656430,880000.0,15.0,1600.0,1,81396.0,3.0,0,0,18.0
1,Hyundai i10 2009model with option,1055000.0,16.0,1100.0,1,71820.0,2.0,0,0,16.0
2,Santro Hyundai 2013 model super fresh 2user...,1515000.0,15.0,1100.0,1,77000.0,2.0,1,0,11.0
3,Santro Hyundai 2013 model super fresh 2user,1515000.0,15.0,1100.0,1,77000.0,2.0,1,0,12.0
4,i10 magna 1200cc,1175000.0,14.0,1200.0,1,62000.0,2.0,0,0,16.0

In [404]:
df = df[df['age'] < 50]

**Saving the Cleaned Data**

In [405]:
df.to_csv("D:/Coding/Exploratory_Data_Analysis/data/Scraped/Clean/cleaned_car_data.csv", index=False)