# Car Dataset Cleaning and Feature Engineering
This notebook demonstrates a step-by-step approach to cleaning, transforming, and preparing a car dataset for analysis. Each section is grouped by logical operations and includes explanations and insights.

## 1. Import Required Libraries
Import the necessary libraries for data manipulation and visualization.

In [1]:
import pandas as pd 
import numpy as np 
import re 
import matplotlib.pyplot as plt

## 2. Load the Dataset
Read the raw car dataset and display the first few rows.

In [2]:
df = pd.read_csv("../Data/car.csv")
df.head()

,Name,Price,Used For,Transmisson,Colour,Make Year,Mileage,Engine (CC),Fuel,Kilometer Run,Waranty,Types
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Manual2WD,Brown,2015,14,1400,Petrol,42000,NaN,NaN
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Auto2WD,Light blue,2005,11,1399,Petrol,87412,NaN,NaN
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,Manual - 2WD,White,2013,NaN,2956,Diesel,60000,NaN,NaN
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,Manual - 4WD,NaN,2017,NaN,NaN,Diesel,NaN,NaN,NaN
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,Auto - 2WD,white,2019,17,1200,Petrol,2400,NaN,NaN

In [3]:
print(len(df))

848

## 3. Initial Data Cleaning
### 3.1 Standardize Column Names
Convert column names to snake_case and remove special characters.

In [4]:
df.columns = (
    df.columns               
      .str.lower()                  # convert to lowercase
      .str.replace('[^a-zA-Z0-9 ]', '', regex=True)   # remove special chars ()&./
      .str.replace(' +', '_', regex=True)  # convert spaces to underscores
)
df.head()

,name,price,used_for,transmisson,colour,make_year,mileage,engine_cc,fuel,kilometer_run,waranty,types
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Manual2WD,Brown,2015,14,1400,Petrol,42000,NaN,NaN
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Auto2WD,Light blue,2005,11,1399,Petrol,87412,NaN,NaN
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,Manual - 2WD,White,2013,NaN,2956,Diesel,60000,NaN,NaN
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,Manual - 4WD,NaN,2017,NaN,NaN,Diesel,NaN,NaN,NaN
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,Auto - 2WD,white,2019,17,1200,Petrol,2400,NaN,NaN

### 3.2 Remove Duplicates
Drop duplicate rows based on the car name.

In [5]:
df.drop_duplicates(subset=["name"], keep="first")

,name,price,used_for,transmisson,colour,make_year,mileage,engine_cc,fuel,kilometer_run,waranty,types
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Manual2WD,Brown,2015,14,1400,Petrol,42000,NaN,NaN
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Auto2WD,Light blue,2005,11,1399,Petrol,87412,NaN,NaN
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,Manual - 2WD,White,2013,NaN,2956,Diesel,60000,NaN,NaN
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,Manual - 4WD,NaN,2017,NaN,NaN,Diesel,NaN,NaN,NaN
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,Auto - 2WD,white,2019,17,1200,Petrol,2400,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
843,Hyundai grand i10 (Hyundai),"रू. 24,50,000",2 years,Manual - 2WD,silver,2020,2025,1200,Petrol,26500,NaN,NaN
844,Well maintained car. Everything is fine. Singl...,"रू. 19,25,000",6 years,Manual2WD,Navy blue,2015,15,1200,Petrol,60000,No,NaN
845,VW Polo 2014 Highline 1200 (Renault),"रू. 19,50,000",7,Manual2WD,Carbon Steel ( Dark Grey),2014,12 to 14,1200,Petrol,60000,NaN,NaN
846,Hyundai i10 magna 2014 (Hyundai),"रू. 17,50,000",NaN,Manual - 2WD,silver,2014,NaN,1200,Petrol,93000,NaN,NaN
847,nissan xtrail 2007 model for sale or exchange ...,"रू. 24,50,000",private use,Auto - 4WD,cream,2007,13,2200,Diesel,60000,no warenty,NaN

## 4. Feature Engineering and Cleaning
### 4.1 Convert Engine Power from KW to CC
Some engine values are in kilowatts (KW). Convert them to cubic centimeters (CC) for consistency.

In [6]:
def convert_kw_to_cc(value):
    if pd.isna(value):
        return value
    
    # Convert to string for processing
    value_str = str(value).strip().lower()
    
    # Check if 'kw' is in the value
    if 'kw' in value_str:
        # Extract numeric part using regex
        match = re.search(r'(\d+\.?\d*)', value_str)
        if match:
            numeric_value = float(match.group(1))
            # Multiply by 24.25 and return
            return numeric_value * 24.25
    
    # Return original value if no 'kw' found
    return value

df['engine_cc']= df['engine_cc'].apply(convert_kw_to_cc)

### 4.2 Clean Numeric Columns
Extract numeric values from columns and convert them to appropriate types.

In [7]:

def clean_numeric_columns(df, columns):
    for col in columns:
        df[col] = df[col].astype(str).str.extract(r'(\d+(?:\.\d+)?)')
        df[col] = pd.to_numeric(df[col], errors='coerce')
    return df

df = clean_numeric_columns(df,['make_year','mileage','engine_cc','kilometer_run'])
df.head()

,name,price,used_for,transmisson,colour,make_year,mileage,engine_cc,fuel,kilometer_run,waranty,types
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Manual2WD,Brown,2015,14.0,1400.0,Petrol,42000.0,NaN,NaN
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Auto2WD,Light blue,2005,11.0,1399.0,Petrol,87412.0,NaN,NaN
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,Manual - 2WD,White,2013,NaN,2956.0,Diesel,60000.0,NaN,NaN
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,Manual - 4WD,NaN,2017,NaN,NaN,Diesel,NaN,NaN,NaN
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,Auto - 2WD,white,2019,17.0,1200.0,Petrol,2400.0,NaN,NaN

### 4.3 Handle Missing and Outlier Values
Identify and handle missing values and outliers in critical columns.

In [8]:
def sixty_percent_or_more_columns_missing(df,critical_columns):
    missing_count = df[critical_columns].isna().sum(axis=1)
    to_drop = missing_count >= 3
    print(f"Length of outliers:{len(df.loc[to_drop, critical_columns])}\n\n")

In [9]:
sixty_percent_or_more_columns_missing(df,['engine_cc', 'make_year', 'price','mileage','kilometer_run'])

Length of outliers:61

#### Insights after cleaning and outlier handling:
- Outliers in kilometer run and engine CC are capped to reasonable values.
- Missing values in critical columns are imputed using domain knowledge and dataset statistics.

## 5. Feature Extraction
### 5.1 Transmission and Drive Type
Split the transmission column into transmission type and drive type for better analysis.

In [10]:
def split_transmisson(value):
    
    #first, let us check if the value is none. 
    if pd.isna(value):
        return (None,None)

    #Lets seperate by space
    value = value.strip()

    #If - is in the value then seperate by that value
    if '-' in value:
        parts = [p.strip() for p in value.split('-')]
        if len(parts) == 2:
            transmission_type = parts[0]
            drive = parts[1]
            return (transmission_type, drive)

    #Finally if the - doesn't exist we seperate alphabetic and numeric/WD parts 
    match = re.match(r"([A-Za-z]+)(.*)", value)
    if match:
        transmission_type = match.group(1)
        drive = match.group(2)
        return(transmission_type,drive)

    return(value,None)  

df[['transmisson_type','drive']] = df['transmisson'].apply(lambda x: pd.Series(split_transmisson(x)))
df.drop('transmisson', axis=1, inplace=True)
df.head()

,name,price,used_for,colour,make_year,mileage,engine_cc,fuel,kilometer_run,waranty,types,transmisson_type,drive
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Brown,2015,14.0,1400.0,Petrol,42000.0,NaN,NaN,Manual,2WD
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Light blue,2005,11.0,1399.0,Petrol,87412.0,NaN,NaN,Auto,2WD
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,White,2013,NaN,2956.0,Diesel,60000.0,NaN,NaN,Manual,2WD
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,NaN,2017,NaN,NaN,Diesel,NaN,NaN,NaN,Manual,4WD
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,white,2019,17.0,1200.0,Petrol,2400.0,NaN,NaN,Auto,2WD

### 5.2 Encoding Categorical Features
Encode transmission type, drive type, and fuel type into binary or ordinal features for modeling.

In [11]:
df['is_automatic'] = (df['transmisson_type'] == 'Auto').astype(int)
df.drop('transmisson_type', axis=1, inplace=True)

In [12]:
df['is_4WD'] = (df['drive'] == '4WD').astype(int)
df.drop('drive', axis=1, inplace=True)

In [13]:
fuel_order = {
    "Petrol": 1,
    "Diesel": 2,
    "Electric": 3,
    "Hybrid": 4
}

df['fuel'] = df['fuel'].map(fuel_order)
df.head()

,name,price,used_for,colour,make_year,mileage,engine_cc,fuel,kilometer_run,waranty,types,is_automatic,is_4WD
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Brown,2015,14.0,1400.0,1,42000.0,NaN,NaN,0,0
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Light blue,2005,11.0,1399.0,1,87412.0,NaN,NaN,1,0
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,White,2013,NaN,2956.0,2,60000.0,NaN,NaN,0,0
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,NaN,2017,NaN,NaN,2,NaN,NaN,NaN,0,1
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,white,2019,17.0,1200.0,1,2400.0,NaN,NaN,1,0

## 6. Final Feature Engineering
Convert make year to car age and drop unnecessary columns.

In [14]:
df['age'] = 2025 - df['make_year']
df.drop('make_year',axis=1,inplace=True)
df.head()

,name,price,used_for,colour,mileage,engine_cc,fuel,kilometer_run,waranty,types,is_automatic,is_4WD,age
0,Hyundai | i20 Active S | TDi | 2015 | Hatchbac...,"रू. 24,75,000रू. 25,00,000",Private Use,Brown,14.0,1400.0,1,42000.0,NaN,NaN,0,0,10
1,Excellent car on sale (Hyundai),"रू. 7,50,000",NaN,Light blue,11.0,1399.0,1,87412.0,NaN,NaN,1,0,20
2,TATA 407 Container (Tata),"रू. 7,00,000",NaN,White,NaN,2956.0,2,60000.0,NaN,NaN,0,0,12
3,4x4 swaraj Mazda (Mahindra),"रू. 6,00,000",NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,0,1,8
4,i20 Active good for used few time (Hyundai),रू. 375,NaN,white,17.0,1200.0,1,2400.0,NaN,NaN,1,0,6

## 7. Save Cleaned Data
Export the cleaned and transformed dataset for further analysis.

In [15]:
df.to_csv("cleaned_data.csv", index=False)

### Summary of Cleaning Steps
- Standardized column names and removed duplicates.
- Converted engine power units and cleaned numeric columns.
- Imputed missing values and capped outliers.
- Extracted and encoded categorical features.
- Saved the final cleaned dataset.

In [16]:
print(len(df))

848